-
  name: 'reorderGlobalContentList'
  uriPattern: 'arsors/globalcontent/reorderList'
  defaults:
    '@package':    'Arsors.GlobalContent'
    '@controller': 'GlobalContent'
    '@action':     'reorder'
    '@format':     'html'