Arsors:
  GlobalContent:
    instanceof:
      - 'Arsors.GlobalContent:GlobalContent'

Neos:
  Neos:
    fusion:
      autoInclude:
        'Arsors.GlobalContent': true
  Fusion:
    defaultContext:
      'Arsors.GlobalContent': 'Arsors\GlobalContent\EelHelper\GlobalContent'
